WebLab/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebLab.DAL.Data;
using WebLab.Extensions;
using WebLab.Models;

namespace WebLab.Controllers
{
    public class CartController : Controller {
        private ApplicationDbContext _context;
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart) {
            _context = context;
            _cart = cart;
        }
        public IActionResult Index() {
            //_cart = HttpContext.Session.Get<Cart>("cart");
            return View(_cart.Items.Values);
        }

        [Authorize]
        public IActionResult Add(int id, string returnUrl) {
            //_cart = HttpContext.Session.Get<Cart>("cart");
            var item = _context.Militaries.Find(id);
            if (item != null) {
                _cart.AddToCart(item);
                //HttpContext.Session.Set<Cart>("cart", _cart);
            }
            return Redirect(returnUrl);
        }

        public IActionResult Delete(int id) {
            //_cart = HttpContext.Session.Get<Cart>("cart"); 
            _cart.RemoveFromCart(id);
            //HttpContext.Session.Set<Cart>("cart", _cart); 
            return RedirectToAction("Index");
        }
    }
}

WebLab/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebLab.DAL.Data;
using WebLab.DAL.Entities;
using WebLab.Extensions;
using WebLab.Models;

namespace WebLab.Controllers
{
    public class ProductController : Controller {
        ApplicationDbContext _context;
        int _pageSize;

        public ProductController(ApplicationDbContext context) {
            _pageSize = 3;
            _context = context;
        }

        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]
        public IActionResult Index(int? group, int pageNo = 1) {
            var militariesFiltered = _context.Militaries.Where(d => !group.HasValue || d.MilitaryGroupId == group.Value);
            // Поместить список групп во ViewData 
            ViewData["Groups"] = _context.MilitaryGroups;

            // Получить id текущей группы и поместить в TempData 
            var currentGroup = group.HasValue ? group.Value : 0;

            ViewData["CurrentGroup"] = currentGroup;

            if (Request.IsAjaxRequest()) {
                return PartialView("_ListPartial", ListViewModel<Military>.GetModel(militariesFiltered, pageNo, _pageSize));
            }
            return View(ListViewModel<Military>.GetModel(militariesFiltered, pageNo, _pageSize));
        }
    }
}

WebLab/Views/Product/Index.cshtml
@model ListViewModel<Military>

@{
    ViewData["Title"] = "Журнал";
}

@{
    var categories = ViewData["Groups"] as IEnumerable<MilitaryGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];

    var text = currentGroup != 0
        ? categories
            .FirstOrDefault(g => g.MilitaryGroupId == currentGroup)?
            .GroupName
        : "Все группы";
}

<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index" asp-controller="Product"
               role="button"
               id="dropdownMenuLink" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                @text
            </a>

            <div class="dropdown-menu"
                 aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item"
                   asp-action="Index"
                   asp-controller="Product">Все</a>

                @foreach (var item in categories) {
                    <a class="dropdown-item"
                       asp-action="Index"
                       asp-controller="Product"
                       asp-route-group="@item.MilitaryGroupId">@item.GroupName</a>
                }
            </div>
        </div>
    </div>
    <div class="col-10">
        <div class="card-group" id="list">
            <partial name="_ListPartial" model="@Model" />
        </div>
        <pager page-current="@Model.CurrentPage" page-total="@Model.TotalPages" action="Index"
               controller="Product" group-id="@currentGroup"></pager>
    </div>
</div>

WebLab/Views/Product/_ListItemPartial.cshtml
@model Military

<div class='card m-2 p-1 col-4'>
    <img src="~/Images/@Model.Image"
         alt='NoImage'
         class="card-img" />
    <div class="card-body">
        <h5 class="card-title">
            @Model.MilitaryName
        </h5>
        <p class="card-text">
            @Model.Description
        </p>
        <div class="card-subtitle badge">
            <h4> @Model.Force калорий</h4>
        </div>
        <!--Разметка кнопки добавления в корзину-->
        <a asp-action="Add"
           asp-controller="Cart"
           asp-route-id="@Model.MilitaryId"
           asp-route-returnUrl="@ViewContext.HttpContext.Request.Path"
           class="btn btn-primary">
            <i class="fa fa-shopping-cart"></i> В корзину
        </a>
    </div>
</div>

WebLab/Views/Product/_ListPartial.cshtml
@model ListViewModel<Military>
@foreach (var item in Model) {
    <partial name="_ListItemPartial" model="@item" />
}