WebLab/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebLab.Extensions;
using WebLab.Models;

namespace WebLab.Components
{
	public class CartViewComponent : ViewComponent {
		private Cart _cart;
		public CartViewComponent(Cart cart) {
			_cart = cart;
		}

		public IViewComponentResult Invoke() {
			//var cart = HttpContext.Session.Get<Cart>("cart") ?? new Cart();
			return View(_cart);
		}
	}
}

WebLab/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using WebLab.Models;

namespace WebLab.Components
{
	public class MenuViewComponent : ViewComponent
	{
		// Инициализация списка элементов меню 
		private List<MenuItem> _menuItems = new List<MenuItem> {
			new MenuItem{ Controller="Home", Action="Index", Text="Lab 8"},
			new MenuItem{ Controller="Product", Action="Index", Text="Каталог"},
			new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"}
		};

		public IViewComponentResult Invoke() {
			//Получение значений сегментов маршрута
			var controller = ViewContext.RouteData.Values["controller"];
			var page = ViewContext.RouteData.Values["page"];
			var area = ViewContext.RouteData.Values["area"];

			foreach (var item in _menuItems) {
				// Название контроллера совпадает? 
				var _matchController = controller?.Equals(item.Controller) ?? false;
				// Название зоны совпадает? 
				var _matchArea = area?.Equals(item.Area) ?? false;
				// Если есть совпадение, то сделать элемент меню активным  
				// (применить соответствующий класс CSS) 
				if (_matchController || _matchArea) {
					item.Active = "active";
				}
			}
			return View(_menuItems);
		}
	}
}

WebLab/Controllers/ImageController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using System.Threading.Tasks;
using WebLab.DAL.Entities;

namespace WebLab.Controllers
{
    public class ImageController : Controller {
        UserManager<ApplicationUser> _userManager;
        IHostingEnvironment _env;

        public ImageController(UserManager<ApplicationUser> mngr, IHostingEnvironment env) {
            _userManager = mngr;
            _env = env;
        }

        public async Task<IActionResult> GetAvatar() {
            var user = await _userManager.GetUserAsync(User);
            if (user == null) return null;
            if (user.AvatarImage != null)
                return File(user.AvatarImage, user.ImageMimeType);
            else {
                var avatarPath = "/Images/avatar.jpg";
                var extProvider = new FileExtensionContentTypeProvider();
                var mimeType = extProvider.Mappings[".png"];
                return File(_env.WebRootFileProvider.GetFileInfo(avatarPath).CreateReadStream(), mimeType);
            }
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WebLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/v4-shims.css" />
</head>
<body>
    @RenderSection("Scripts", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" href="#">803325_Петько</a>
                @await Component.InvokeAsync("Menu")
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
        </div><!-- container - конец -->
    </header><!-- headerstrip - конец -->



    <main class="container">
        @RenderBody()
    </main>



    <footer>
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

WebLab/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using WebLab.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager
<!-- Информация пользователя -->
@if (signInManager.IsSignedIn(User)) {
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @*<img src="@Url.Action("GetAvatar","Image")" width="30" alt="User" class="rounded bg-light" />*@
            <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded bg-light" />
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded bg-light" />@User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Product" asp-action="UserProducts">Мои товары</a>
            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit" value="Log off" class="dropdown-item" />
            </form>
        </div>
    </div>
} else {
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">Зарегистрироваться
            </a>
        </li>
    </ul>
}
<!-- Информация пользователя - конец -->